In [109]:
import numpy as np

In [110]:
tile_rewards = np.array([[0.02, 0.01, -0.02, 0.03], [0, 0.01, 0.02, 0.01], [0.02, -0.01, 0.01, 0], [0.02, 0.01, 0.02, 0.01]])

In [111]:
print(tile_rewards)

[[ 0.02  0.01 -0.02  0.03]
 [ 0.    0.01  0.02  0.01]
 [ 0.02 -0.01  0.01  0.  ]
 [ 0.02  0.01  0.02  0.01]]


In [112]:
startX, startY = 1,0
EndX, EndY = 2,3

Actions = ['up','down','left','right']
GameOver = False

In [113]:
board = np.zeros([4,4])
print(board)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [114]:
def move(currentPos):
    prevPosition = currentPos
    Action = np.random.choice(Actions)
    if Action == 'up':
        currentPos = (currentPos[0]-1,currentPos[1])
    elif Action == 'down':
        currentPos = (currentPos[0]+1,currentPos[1])
    elif Action == 'left':
        currentPos = (currentPos[0],currentPos[1]-1)
    elif Action == 'right':
        currentPos = (currentPos[0],currentPos[1]+1)
    if (currentPos[0] >= 0) and (currentPos[0] <= 3):
        if (currentPos[1] >= 0) and (currentPos[1] <= 3):
                return currentPos, Action
    return move(prevPosition)


In [115]:
print(move((0,0))[1])

down


In [116]:
def checkWin(currentPos):
    if currentPos == (EndX,EndY):
        GameOver = True
        return GameOver

In [117]:
def reward(currrentPos):
    if currrentPos == (EndX, EndY):
        return 1
    else:
        return tile_rewards[currrentPos[0],currrentPos[1]]

In [ ]:
def play(rounds=1):
    i = 0
    currentPosition = (startX, startY)
    singlePolicy = []
    OverallPolicy = []
    while i < rounds:
        if checkWin(currentPosition):
            reward(currentPosition)
            # singlePolicy.append('Win')
            OverallPolicy.append(singlePolicy)
            currentPosition = (startX, startY) # reset
            singlePolicy = [] # reset
            i += 1
        else:
            movement = move(currentPosition)
            currentPosition = movement[0]
            ActionToReachCurrentPosition = movement[1]
            reward(currentPosition)
            # print((currentPosition, ActionToReachCurrentPosition, reward(currentPosition)))
            singlePolicy.append((currentPosition, ActionToReachCurrentPosition, reward(currentPosition)))
    return OverallPolicy

In [120]:
play(50)

[[((2, 0), 'down', 0.02),
  ((2, 1), 'right', -0.01),
  ((2, 2), 'right', 0.01),
  ((3, 2), 'down', 0.02),
  ((2, 2), 'up', 0.01),
  ((2, 3), 'right', 1)],
 [((1, 1), 'right', 0.01),
  ((1, 2), 'right', 0.02),
  ((1, 1), 'left', 0.01),
  ((1, 2), 'right', 0.02),
  ((2, 2), 'down', 0.01),
  ((3, 2), 'down', 0.02),
  ((3, 1), 'left', 0.01),
  ((2, 1), 'up', -0.01),
  ((3, 1), 'down', 0.01),
  ((2, 1), 'up', -0.01),
  ((3, 1), 'down', 0.01),
  ((2, 1), 'up', -0.01),
  ((2, 2), 'right', 0.01),
  ((2, 3), 'right', 1)],
 [((2, 0), 'down', 0.02),
  ((1, 0), 'up', 0.0),
  ((0, 0), 'up', 0.02),
  ((1, 0), 'down', 0.0),
  ((1, 1), 'right', 0.01),
  ((0, 1), 'up', 0.01),
  ((0, 0), 'left', 0.02),
  ((0, 1), 'right', 0.01),
  ((0, 2), 'right', -0.02),
  ((1, 2), 'down', 0.02),
  ((1, 1), 'left', 0.01),
  ((0, 1), 'up', 0.01),
  ((0, 0), 'left', 0.02),
  ((1, 0), 'down', 0.0),
  ((1, 1), 'right', 0.01),
  ((1, 0), 'left', 0.0),
  ((2, 0), 'down', 0.02),
  ((2, 1), 'right', -0.01),
  ((2, 0), 'left'